ALTER TABLE users
  ADD COLUMN IF NOT EXISTS completed_jobs INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS no_show_cancellations INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS completion_rate NUMERIC(5,2) DEFAULT NULL;
