ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS overrun_notified_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS delay_response VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS tasker_new_eta TIMESTAMPTZ DEFAULT NULL;
